### ISSUE TITLE
I dont know why this keeps coming up. Help!

### ISSUE THREAD

**Issue by jso-07** [sparkfun/LilyPad_MP3_Player#1]
Arduino: 1.6.1 (Mac OS X), Board: "LilyPad Arduino, ATmega328"

/Users/jasmineangelaso/Documents/Arduino/libraries/SFEMP3Shield/SFEMP3Shield.cpp:25:37: error: variable 'bitrate_table' must be const in order to be put into read-only section by means of '**attribute**((progmem))'
 PROGMEM uint16_t bitrate_table[15][6] = {
                                     ^
Error compiling.

  This report would have more information with
  "Show verbose output during compilation"
  enabled in File > Preferences.

**Comment by embeddedgenius** [comment]
Edit:
changing:
   PROGMEM uint16_t bitrate_table[15][6] = {
to:
   PROGMEM const uint16_t bitrate_table[15][6] = {

Resolved this...

**Comment by mgrusin** [comment]
We've updated the SFE MP3 Player library included in this repository to the most recent version, which fixes the above issue and should compile cleanly in recent Arduino IDEs (1.6.7 etc.) Please let us know if you run into further problems.
