### ISSUE TITLE
Player - 'Next Track' issues

### ISSUE THREAD

**Issue by Joshoeah** [sparkfun/LilyPad_MP3_Player#4]
Hi there,

As discussed with Sparkfun support, Player.ino appears to have issues with moving to the next track. Using a Lilypad MP3 with two speakers connected and an SD Card formatted to FAT32 with 7 files on it (all MP3):

**Whilst playing**
-  Turning rotary encoder CW results in it skipping from whichever track is playing to Track 1, then Track 5, then Track 1, then back to Track 5 - it never selects any other track.

- Allowing a track to play through and 'advance' to the next one automatically results in the same behaviour - Track 1, 5, 1, 5 over and over. 

- Turning rotary encoder CCW results in skipping to 'previous' track exactly as expected. I anticipate this is due to the different code used to search 'backwards' through the SD card.

**Whilst not playing** (monitored through Serial)
- Turning rotary encoder either direction results in the device correctly moving through tracks sequentially - exactly as expected. 

I have observed no other issues outside of this - though looking through the code I simply cannot see why I'm experiencing this problem. I have even monitored HEX values of the encoder and these are consistent - whether playing or not - so it does not appear to be an issue with the encoder or the code controlling it. Rather, it appears this issue is with selecting the next file on the SD Card.

I have noticed some of the libraries have been updated since this code was posted here and on the Sparkfun site - I tried to update these in the Arduino IDE, but this resulted in errors regarding SDFatUtil and the code would no longer compile.

Hope that's enough information for you / you might be able to help with narrowing this issue down - I'm a bit lost!

**Comment by mgrusin** [comment]
Hi Josh, that's an excellent bug report, and a mysterious one. I'll be sure to take a look at this next week, but in the meantime you might turn on serial debugging output at the top of the code to see if it prints out any clues. There could also be something weird with the SD card. You might try low-level formatting it, and also see if you can read all the files off of it on a normal computer.

**Comment by Joshoeah** [comment]
Hey Mike - thanks for the help. Can confirm I've formatted the SD card a few times on various computers just to check and tried an alternative one too - had no luck either way so far. Serial debugging doesn't seem to show up anything unusual - everything starts up as expected with no error messages. Switching between tracks (whether CW or CCW) whilst playing gives the usual 'Stopping playback' and then next file name.
Just in case - I'll grab a fresh SD card and try some alternative files and will reply here if I have any luck. Thanks in advance for any light you might be able to shed on the matter! Let me know if I can pull any extra info from the serial monitor for you.

**Comment by Joshoeah** [comment]
Quick update: fresh 1GB SD, tested formatted as both FAT and FAT32 - exactly the same behaviour, no changes in either case.

**Comment by Joshoeah** [comment]
Tried updating to most recent version SDFat and removing all references to SDFatUtil (this was what was throwing errors during compile). Managed to get the code to compile and upload, but this just resulted in it getting stuck after initialising the MP3 Chip - no error messages thrown, it just never fully 'started up'. Encoder stayed dark, no files would play.

Think we can safely conclude that 'something' has changed in the way SDFat works and the current library is incompatible without a few changes to the code. This is a little bit above my knowledge base, unfortunately! Have reverted back to the library uploaded here and shall keep testing.

**Comment by Joshoeah** [comment]
A little serial monitoring shows the following:

- Tracks appear on the card slightly out of order despite naming them all 1 through 8.mp3 and ensuring they were in this order using a laptop. **Lilypad reads them as 1,6,2,3,4,5,7,8.**
- Rotating CW whilst not playing results in moving through tracks sequentially then looping back to the start
- Rotating CW whilst playing results in just the first three tracks (1,6,2) playing, then looping back to 1.

Serial output below, in case I'm missing something obvious:

**Startup & rotating CW whilst not playing**

> Lilypad MP3 Player
Free RAM = 963
Initializing SD card... 
OK
Initializing MP3 chip... 
OK
current track: 1MP3\~1.MP3
current track 6MP3\~1.MP3
current track 2MP3\~1.MP3
current track 3MP3\~1.MP3
current track 4MP3\~1.MP3
current track 5MP3\~1.MP3
current track 7MP3\~1.MP3
current track 8MP3\~1.MP3
current track 1MP3\~1.MP3
current track 6MP3\~1.MP3
current track 2MP3\~1.MP3
current track 3MP3\~1.MP3
current track 4MP3\~1.MP3
current track 5MP3\~1.MP3
current track 7MP3\~1.MP3
current track 8MP3\~1.MP3

**Rotating CW whilst playing**
>playing 1MP3\~1.MP3... result 0
stopping playback
playing 6MP3\~1.MP3... result 0
current track 6mp3\~1.mp3
stopping playback
playing 2MP3\~1.MP3... result 0
current track 2mp3\~1.mp3
stopping playback
playing 1MP3\~1.MP3... result 0
current track 1mp3\~1.mp3
stopping playback
playing 6MP3\~1.MP3... result 0
current track 6mp3\~1.mp3
stopping playback
playing 2MP3\~1.MP3... result 0
current track 2mp3\~1.mp3
stopping playback

**Comment by mgrusin** [comment]
Hi Josh, give the Rotary_Encoder_Demo.ino a try (in examples) when you get a chance. With the serial window open to 9600 baud it should show smooth operation of the rotary encoder. If it doesn't there may be a hardware problem with the encoder, which could explain some of this behavior.

It's worth noting that the player sketch doesn't do any alphabetizing of the files it finds; it plays them in the order in which they're physically stored on the SD card. To get them to play in a specific order you might try formatting the card then copying your files to it one-by-one in the order you prefer.

The way player works, especially when you want the previous file (for which there is no SDfat function) was always a little hacky due to the primitive way SDfat traverses directories. I do recall seeing that SDfat had completely changed some of their routines (hopefully for the better) but since that thoroughly broke the existing software we haven't gone back to rewrite everything. It might be time to do that now. But if you use all of the libraries included in this repo (deleting newer ones from your libraries folder to avoid confusion) it "should" work.

Let me know what you find.

**Comment by Joshoeah** [comment]
Hey Mike, I gave Rotary_Encoder_Demo.ino a shot just now and the encoder spins smoothly - numbers increase sequentially as far as I turn it, then decrease the other way. No issues with button press (or hold) - all behaving as expected.

Ahh I got'cha - I did wonder! Either way, moving forward (CW) whilst playing just runs the first three tracks it finds on the card (1, 6, then 2 in this case) before looping back to 1 again. The things I find most strange is getNextTrack clearly has no issues moving through files - it smoothly moves from track to track when playback is paused as well as when moving backwards through the tracks (CCW on the encoder).

I've since reverted to the libraries you have here as suggested. I don't think I'm capable enough to rewrite this with the new libraries - I got lost when I did try - but I could try and hack something together. The prop I'm building is for an event on the 5th of August, so if necessary I'll just ensure it's used to skip through tracks backwards and forego going forwards - only problem with this being when it reaches the end of a track it'll revert back to the 1,2,6 loop. If all else fails I might just have to make a singular long MP3 with all of the files in the order required - that'll work 100% :)

Thanks for the help!

**Comment by Joshoeah** [comment]
Okay - got it! Managed to get it to compile using the latest version of SdFat (updated direct from the Library Manager) and **that's fixed it!** Tracks now smoothly advance sequentially whether using the encoder or when reaching the end of a track.

Steps taken for future reference (probably hacky, but hey, it works):

- **Removed \#include SdFatUtil.h from SFEMP3Shield.h** - not used in new SdFat library
- **Removed \#include SdFatUtil.h from Player.ino** - not used in new SdFat library
- **Changed Line 611 in Player.ino**, amending file.getFileName(track) to **file.getName(track,13)**. This is the key change that got it working with the new SdFat, since getFileName has been deprecated. file.getName has a new parameter for length, hence the 13. Not sure if this is the right way to do it, but it works!

Worth noting that SdFat now supports long names, so the full track name could be pulled - if this is of use to anyone in the future.

I did have a funny issue with 'FreeRam' in line 186 - the code would no longer compile and started throwing errors about this not being defined. Since it wasn't critical, I've just commented it out for now.

Hope this helps anybody in future - the changes were ultimately quite simple to make and the sketch now works perfectly!

**Comment by Joshoeah** [comment]
Quick supplementary comment to this - my files were ultimately stored with the naming format 1.mp3, 2.mp3, 3.mp3, etc... I found that longer names were a bit unreliable and could result in the track being skipped. **I imagine this is due to me specifying length parameter as '13'** - though I admittedly have not had chance to check since the Lilypad has been secured into the prop.

**I also noted issues with tracks not starting immediately** - seemingly taking a long time to 'load', with several seconds of silence between them. **This was resolved by using [MP3tag](https://www.mp3tag.de/en/index.html) to strip every bit of metadata**, including any cover art, from the files. After doing so I found files loaded instantly and skipping / playing seemed far more responsive.

**Comment by mgrusin** [comment]
Hi Josh, well done! I'm very glad you got it working, and thank you for giving us the steps it took to do so. I believe your solution will work as long as you don't have two filenames that share the same first 13 characters; otherwise it may have problems finding the previous file. But that's an easy enough restriction to work around. When I have time I'll dig into the new SDfat and update everything. Thanks again and again nicely done.
